# Generated by Django 3.1.8 on 2022-08-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('account', models.IntegerField(default=0)),
                ('collecttime', models.DateField(auto_now=True)),
                ('cfrate', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SettingTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolname', models.CharField(default='宜宾学院', max_length=100)),
                ('ojname', models.CharField(default='YBUOJ', max_length=100)),
                ('openwiki', models.BooleanField(default=True)),
                ('openlanguage', models.CharField(default='C++|C|Python3|Python2|Swift5.1|Java', max_length=500)),
                ('openoi', models.BooleanField(default=True)),
                ('openstatus', models.BooleanField(default=True)),
                ('openvisitor', models.BooleanField(default=True)),
                ('openregister', models.BooleanField(default=True)),
                ('openselfstatus', models.BooleanField(default=True)),
            ],
        ),
    ]
